#!/bin/bash
# Author: PietroVN
# Deps: mpv, youtube-dl(or any fork), search (included), curl, sed
# Examples:
# video anime:<anime name>			| Search for anime with this name
# video youutube:<video name>		| Search for a video with this name
# video url:<url>					| Play specified url

# Include search
. /usr/local/bin/search

# Command
command=$@

_play() {
	# Detect mode
	case ${command} in
		*"youtube:"*)
				# Leave only the title on command
				command=$(sed 's/youtube://g' <<< ${command})

				# Search
				search _youtube:${command}

				# 
				echo "Select video:"
				read video_number
				video=$(cat ${tmp_videos} | sed -n ${video_number}p)

				# Play
				mpv ${youtube}${video}
		;;
		*"anime:"*)

				# Leave only the title on command
				command=$(sed 's/anime://g' <<< ${command})

				# Search
				search _anime:${command}

				# 
				echo "Select video:"
				read video_number
				video=$(cat ${tmp_videos} | sed -n ${video_number}p)

				# Play
				mpv ${video}

		;;
		*"url:"*)
			
		;;
	esac
}

# Check if command is empty
[[ -z ${command} ]] && echo "Empty command"

# Play function
_play

#case ${command} in
#	*"search"*)
#		_search
#	;;
#esac
